spring:
  datasource:
    url: jdbc:oracle:thin:@:1521/
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

gai:
  output-directory: /opt/scef/gai/staging/sit
  sftp:
    enabled: true
    host:
    username: opiemdv
    password: ${SFTP_PASSWORD}
    remote-directory: ${GAI_SFTP_REMOTE_DIR}   # TODO: confirm with GAI team
