-- PSE Month-End Attribute Query
SELECT
    'A' as RECORD_TYPE,
    ai.ADJ_INVENTORY_ID as RECORD_ID,
    'PSE_MONTH_END_VALUE' as ATTRIBUTE_NAME,
    ai.NEW_VALUE as ATTRIBUTE_VALUE,
    'NUMERIC' as ATTRIBUTE_TYPE,
    ai.TRANSACTION_CCY as ATTRIBUTE_UNIT
FROM ADJUSTMENT_INVENTORY ai
WHERE ai.ATTRIBUTE_NAME = 'PSE_MONTH_END'
  AND ai.EFFECTIVE_DATE = TO_DATE(:cobDate, 'YYYY-MM-DD')
  AND EXTRACT(DAY FROM ai.EFFECTIVE_DATE) =
      EXTRACT(DAY FROM LAST_DAY(ai.EFFECTIVE_DATE))
ORDER BY ai.ADJ_INVENTORY_ID