-- PSE Month-End Event Query
SELECT
    'E' as RECORD_TYPE,
    TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') as EVENT_TIMESTAMP,
    'PSE_MONTH_END_ADJUSTMENT' as EVENT_TYPE,
    ai.ADJ_INVENTORY_ID as EVENT_ID,
    'SCEF' as SOURCE_SYSTEM,
    ai.ADJUSTMENT_POSTING_STATUS as EVENT_STATUS
FROM ADJUSTMENT_INVENTORY ai
WHERE ai.ATTRIBUTE_NAME = 'PSE_MONTH_END'
  AND ai.EFFECTIVE_DATE = TO_DATE(:cobDate, 'YYYY-MM-DD')
  AND EXTRACT(DAY FROM ai.EFFECTIVE_DATE) =
      EXTRACT(DAY FROM LAST_DAY(ai.EFFECTIVE_DATE))
ORDER BY ai.ADJ_INVENTORY_ID