-- Stress Exposure Record Query
SELECT
    'R' as H,
    se.STRESS_RUN_ID as ADJ_INVENTORY_ID,
    se.SCENARIO_ID as ADJUSTMENT_UPLOAD_ID,
    'Stress Exposure Adjustment' as ADJUSTMENT_TYPE,
    TO_CHAR(se.COB_DATE, 'YYYY-MM-DD') as EFFECTIVE_DATE,
    TO_CHAR(se.POSTED_DATE, 'YYYY-MM-DD') as POSTED_DATE,
    se.CHECKER_ID as CHECKER_SOEID,
    se.MAKER_ID as MAKER_SOEID,
    'STRESS_EXPOSURE' as ATTRIBUTE_NAME,
    se.BASE_EXPOSURE as OLD_VALUE,
    se.STRESSED_EXPOSURE as NEW_VALUE,
    '161534' as ORIGINAL_CSI,
    se.RUN_STATUS as ADJUSTMENT_POSTING_STATUS,
    se.EXPOSURE_CCY as TRANSACTION_CCY,
    'CALCULATED' as ADJUSTMENT_METHOD,
    se.REASON_CODE,
    se.SUB_REASON_CODE,
    se.RUN_STATUS as EVENT_STATUS,
    'DAILY' as RECURRENCE,
    'SCEF' as ADJUSTING_SYSTEM,
    'D' as FREQUENCY,
    se.REQUESTOR_ID as REQUESTOR_SOEID,
    se.ACCOUNT_ID as STANDARD_ACCOUNT,
    se.BUSINESS_UNIT as FRS_BU,
    se.BALANCE_TYPE
FROM STRESS_EXPOSURE se
WHERE se.COB_DATE = TO_DATE(:cobDate, 'YYYY-MM-DD')
  AND se.SCENARIO_TYPE = 'REGULATORY'
ORDER BY se.STRESS_RUN_ID