-- Stress Exposure Event Query
SELECT
    'E' as RECORD_TYPE,
    TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') as EVENT_TIMESTAMP,
    'STRESS_EXPOSURE_ADJUSTMENT' as EVENT_TYPE,
    se.STRESS_RUN_ID as EVENT_ID,
    'SCEF' as SOURCE_SYSTEM,
    se.RUN_STATUS as EVENT_STATUS
FROM STRESS_EXPOSURE se
WHERE se.COB_DATE = TO_DATE(:cobDate, 'YYYY-MM-DD')
  AND se.SCENARIO_TYPE = 'REGULATORY'
ORDER BY se.STRESS_RUN_ID