-- Stress Exposure Attribute Query
SELECT
    'A' as RECORD_TYPE,
    se.STRESS_RUN_ID as RECORD_ID,
    'STRESS_EXPOSURE_AMOUNT' as ATTRIBUTE_NAME,
    se.STRESSED_EXPOSURE as ATTRIBUTE_VALUE,
    'NUMERIC' as ATTRIBUTE_TYPE,
    se.EXPOSURE_CCY as ATTRIBUTE_UNIT
FROM STRESS_EXPOSURE se
WHERE se.COB_DATE = TO_DATE(:cobDate, 'YYYY-MM-DD')
  AND se.SCENARIO_TYPE = 'REGULATORY'
ORDER BY se.STRESS_RUN_ID