-- SWWR Flag Attribute Query
SELECT
    'A' as RECORD_TYPE,
    ai.ADJ_INVENTORY_ID as RECORD_ID,
    'SWWR_FLAG' as ATTRIBUTE_NAME,
    ai.SWWR_FLAG_INDICATOR as ATTRIBUTE_VALUE,
    'STRING' as ATTRIBUTE_TYPE,
    NULL as ATTRIBUTE_UNIT
FROM ADJUSTMENT_INVENTORY ai
WHERE ai.ATTRIBUTE_NAME = 'SWWR'
  AND ai.EFFECTIVE_DATE = TO_DATE(:cobDate, 'YYYY-MM-DD')
  AND ai.ADJUSTMENT_TYPE LIKE '%SWWR Flag%'
ORDER BY ai.ADJ_INVENTORY_ID