-- SWWR Recovery Attribute Query
SELECT
    'A' as RECORD_TYPE,
    sr.RECOVERY_ID as RECORD_ID,
    'SWWR_RECOVERY_RATE' as ATTRIBUTE_NAME,
    sr.RECOVERY_RATE as ATTRIBUTE_VALUE,
    'NUMERIC' as ATTRIBUTE_TYPE,
    'PCT' as ATTRIBUTE_UNIT
FROM SWWR_RECOVERY sr
WHERE sr.COB_DATE = TO_DATE(:cobDate, 'YYYY-MM-DD')
ORDER BY sr.RECOVERY_ID