-- SWWR Recovery Record Query
SELECT
    'R' as H,
    sr.RECOVERY_ID as ADJ_INVENTORY_ID,
    sr.RECOVERY_UPLOAD_ID as ADJUSTMENT_UPLOAD_ID,
    'SWWR Recovery Adjustment' as ADJUSTMENT_TYPE,
    TO_CHAR(sr.EFFECTIVE_DATE, 'YYYY-MM-DD') as EFFECTIVE_DATE,
    TO_CHAR(sr.POSTED_DATE, 'YYYY-MM-DD') as POSTED_DATE,
    sr.CHECKER_SOEID,
    sr.MAKER_SOEID,
    'SWWR_RECOVERY' as ATTRIBUTE_NAME,
    sr.ORIGINAL_AMOUNT as OLD_VALUE,
    sr.RECOVERY_AMOUNT as NEW_VALUE,
    '161534' as ORIGINAL_CSI,
    sr.RECOVERY_STATUS as ADJUSTMENT_POSTING_STATUS,
    sr.RECOVERY_CCY as TRANSACTION_CCY,
    sr.RECOVERY_METHOD as ADJUSTMENT_METHOD,
    sr.REASON_CODE,
    sr.SUB_REASON_CODE,
    sr.RECOVERY_STATUS as EVENT_STATUS,
    'MONTHLY' as RECURRENCE,
    'SCEF' as ADJUSTING_SYSTEM,
    'M' as FREQUENCY,
    sr.REQUESTOR_SOEID,
    sr.ACCOUNT_ID as STANDARD_ACCOUNT,
    sr.BUSINESS_UNIT as FRS_BU,
    sr.BALANCE_TYPE
FROM SWWR_RECOVERY sr
WHERE sr.COB_DATE = TO_DATE(:cobDate, 'YYYY-MM-DD')
ORDER BY sr.RECOVERY_ID