-- SWWR Flag Event Query
SELECT
    'E' as RECORD_TYPE,
    TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') as EVENT_TIMESTAMP,
    'SWWR_FLAG_ADJUSTMENT' as EVENT_TYPE,
    ai.ADJ_INVENTORY_ID as EVENT_ID,
    'SCEF' as SOURCE_SYSTEM,
    ai.ADJUSTMENT_POSTING_STATUS as EVENT_STATUS
FROM ADJUSTMENT_INVENTORY ai
WHERE ai.ATTRIBUTE_NAME = 'SWWR'
  AND ai.EFFECTIVE_DATE = TO_DATE(:cobDate, 'YYYY-MM-DD')
  AND ai.ADJUSTMENT_TYPE LIKE '%SWWR Flag%'
ORDER BY ai.ADJ_INVENTORY_ID